version: '3.8'

services:
  # 前端服务
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # 后端服务
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URI=mysql://objectdetect:objectdetect@db/objectdetect
      - SECRET_KEY=dev_secret_key
      - JWT_SECRET_KEY=dev_jwt_secret_key
      - UPLOAD_FOLDER=/app/uploads
      - MODEL_FOLDER=/app/models
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_models:/app/models

  # 数据库服务
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=objectdetect
      - MYSQL_USER=objectdetect
      - MYSQL_PASSWORD=objectdetect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 开发工具
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mysql_data:
  backend_uploads:
  backend_models: 